name: Automerge on Test Pass

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        run: |
          npm install
          npx jest htmlStructure.test.js

      - name: Merge PR if tests pass
        if: ${{ github.event_name == 'pull_request' && success() }}
        run: |
          # Assuming the default branch is 'main'
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin main
